#!/usr/bin/env python3
##
## EPITECH PROJECT, 2019
## 106bombyx
## File description:
## Maxime ELEONORE
##

from sys import *
from math import *


def option1():
    try:
        n = int(argv[1])
        k = float(argv[2])
        i = 1

        while i <= 100:
            print(i, end=' ')
            print("%.2f" % n)
            n = k * n * ((1000 - n) / 1000)
            i += 1
    except:
        exit(84)


def option2():
    try:
        k = 1.00
        j = 1
        i0 = float(argv[2])
        i1 = float(argv[3])

        while k <= 4:
            n = float(argv[1])
            while j < i0:
                n = k * n * ((1000 - n) / 1000)
                if n < 0:
                    n = 0.00
                j += 1
            while j <= i1:
                print("%.2f" % k, "%.2f" % n)
                n = k * n * ((1000 - n) / 1000)
                if n < 0:
                    n = 0.00
                j += 1
            j = 1
            k += 0.01
    except:
        exit(84)


def my_h():
    print("USAGE")
    print("\t./106bombyx n [k | i0 i1]\n")
    print("DESCRIPTION")
    print("\tn\tnumber of first generation individuals")
    print("\tk\tgrowth rate from 1 to 4")
    print("\ti0\tinitial generation (included)")
    print("\ti1\tfinal generation (included)")


def bombyx():
    nb = len(argv)

    if nb == 2 and argv[1] == "-h":
        my_h()
    elif nb == 3:
        if float(argv[1]) > 0 and float(argv[2]) > 0:
            option1()
        else:
            exit(84)
    elif nb == 4:
        if float(argv[1]) > 0 and float(argv[2]) > 0 and float(argv[3]) > 0:
            option2()
        else:
            exit(84)
    else:
        exit(84)

try:
    bombyx()
except:
    exit(84)